### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by dignifiedquire** [cucumber-ltd/share-primus#3]
Please? Maybe? Publish Much Npm wow

**Comment by aslakhellesoy** [comment]
Sure can do. I just need to get rid of the ShareJS SHA dependency in package.json so that you can pick your own (more recent) SHA. It doesn't look like ShareJS is going to be released any time soon, but the occasional bug fix still seems to be happening.

**Comment by dignifiedquire** [comment]
Yeah I'm using my own fork as well. I suggest making it a `peerDependency` this way one can easily swap out the different versions/forks.

**Comment by aslakhellesoy** [comment]
I'm not sure how we can make it a `peerDependency` since share-primus will not work with the latest release of ShareJS - `0.7.0-alpha9`. I don't think npm considers `git://github.com/share/ShareJS.git#d38587dacf42214aa4b982285e471ae27209df9c` to be `>= 0.7.0-alpha9`. And if we make the peer dependency `git://github.com/share/ShareJS.git#d38587dacf42214aa4b982285e471ae27209df9c` I don't think _anything_ (such as your fork) will be considered `>=`.

Unless I have misunderstood peer dependencies (I just learned about them) I think we have to make it a `devDependency`.

**Comment by aslakhellesoy** [comment]
Done! Grab 0.0.2.

**Comment by dignifiedquire** [comment]
Great thanks, will try how it works on monday :)
